version: "3.2"

services:
    # fhir db
    fhir-appliance-db:
        build:
            context: ./fhir/db
            dockerfile: Dockerfile
        container_name: fhir-appliance-db
        hostname: localhost
        environment:
            - ACCEPT_EULA="Y"
            - SA_PASSWORD=5tMunG050nFh1R
            - MSSQL_PID=Developer #Other options available: https://hub.docker.com/_/microsoft-mssql-server
        ports:
            - 1433:1433
        networks:
            - ward_watcher

    # fhir appliance
    fhir-appliance:
        image: synaneticsltd/synfhir-store:linux-beta-v3.1.1
        restart: always
        container_name: fhir-appliance
        environment:
            - METRICSENABLE=false
            - NAMESPACE=fhir-appliance
            - NODE_ENV=development
            - SERVICEDIR=services
            - SERVICES=**/*.service.js
        env_file:
            - ./fhir/.env
        ports:
            - 3443:443
            - 3880:3880
        depends_on:
            - fhir-appliance-db
        volumes:
            - ./fhir/ssl:/app/ssl
            - ./fhir/jwt:/app/jwt
        networks:
            - ward_watcher

    # ward-watcher app        
    app-session:
        image: redis:alpine
        container_name: app-session
        ports:
            - 6379:6379
        networks:
            - ward_watcher

    app-database:
        build:
            context: ./app/db
            dockerfile: Dockerfile
        container_name: app-database
        hostname: localhost
        environment:
            - ACCEPT_EULA="Y"
            - SA_PASSWORD=5tMunG050nFh1R
            - MSSQL_PID=Developer
        ports:
            - 1434:1433
        networks:
            - ward_watcher

    integration-engine-db:
        image: postgres
        environment:
            - POSTGRES_USER=mirthdb
            - POSTGRES_PASSWORD=mirthdb
            - POSTGRES_DB=mirthdb
        expose:
            - 5432
        networks:
            - ward_watcher

    integration-engine:
        image: nextgenhealthcare/connect
        environment:
            - DATABASE=postgres
            - DATABASE_URL=jdbc:postgresql://integration-engine-db:5432/mirthdb
            - DATABASE_MAX_CONNECTIONS=20
            - DATABASE_USERNAME=mirthdb
            - DATABASE_PASSWORD=mirthdb
            - DATABASE_MAX_RETRY=2
            - DATABASE_RETRY_WAIT=10000
            - KEYSTORE_STOREPASS=docker_storepass
            - KEYSTORE_KEYPASS=docker_keypass
            - VMOPTIONS=-Xmx512m
        volumes: 
            - ./mirth/extensions:/opt/connect/custom-extensions
            - ./mirth/data/appdata:/opt/connect/appdata
        ports:
            - 8080:8080/tcp
            - 8443:8443/tcp
        depends_on:
            - integration-engine-db
        networks:
            - ward_watcher

    integration-engine-master-data:
        build:
            context: ./mirth/db
            dockerfile: Dockerfile
        container_name: integration-engine-master-data
        hostname: localhost
        environment:
            - ACCEPT_EULA="Y"
            - SA_PASSWORD=5tMunG050nFh1R
            - MSSQL_PID=Developer
        ports:
            - 1435:1433
        networks:
            - ward_watcher

networks:
    ward_watcher:

volumes:
    data:
