version: "3.2"

services:

    app:
        build:
            context: ../
            dockerfile: Dockerfile
        container_name: app
        environment:
            - NAMESPACE=ward-watcher
            - NODE_ENV=development
            - SERVICEDIR=services
            - SERVICES=**/*.service.js
        env_file:
            ../.env
        depends_on:
            - fhir-appliance
            - integration-engine
            - app-database
            - app-session
        ports:
            - 3000:3000
        volumes:
            - ./app/auth:/app/auth
        networks:
            - ward_watcher

networks:
    ward_watcher:

volumes:
    data:
